import {test} from 'node:test';import assert from 'node:assert/strict';
import {createBanner,variation,SIZES,TEMPLATES,validateProject,wrapText} from '../public/engine.js';
import {zipStore} from '../public/zip.js';
test('three templates reflow within all five requested sizes',()=>{for(const t of TEMPLATES)for(const r of Object.keys(SIZES)){const b=createBanner({main:'[단순분류]\n원하는 날 출근해요',sub:'주말 근무',footnote:'근무 조건 확인'},r,t.id);assert.deepEqual([b.width,b.height],SIZES[r]);for(const l of b.layers){assert.ok(l.x>=0&&l.y>=0&&l.w>0&&l.h>0);assert.ok(l.x+l.w<=b.width+.01,l.role);assert.ok(l.y+l.h<=b.height+.01,l.role);}assert.ok(b.layers.some(l=>l.role==='메인 카피'&&l.type==='text'));}});
test('variation preserves edited text, colors, crop, hidden state and custom objects',()=>{const b=createBanner({main:'원본'});const main=b.layers.find(l=>l.role==='메인 카피');main.text='수정된 카피';main.color='#ff0000';b.layers.find(l=>l.role==='사진').cropX=28;b.layers.find(l=>l.role==='서브 카피').visible=false;b.layers.push({...main,id:'custom',role:'custom',name:'추가 텍스트'});const v=variation(b,'4:5');assert.equal(v.layers.find(l=>l.role==='메인 카피').text,'수정된 카피');assert.equal(v.layers.find(l=>l.role==='메인 카피').color,'#ff0000');assert.equal(v.layers.find(l=>l.role==='사진').cropX,28);assert.equal(v.layers.find(l=>l.role==='서브 카피').visible,false);assert.ok(v.layers.some(l=>l.role==='custom'));assert.equal(b.ratio,'1:1');});
test('deleted standard layers do not come back during reflow',()=>{const b=createBanner({});b.layers=b.layers.filter(l=>l.role!=='CTA');assert.ok(!variation(b,'9:16').layers.some(l=>l.role==='CTA'));});
test('import rejects remote image URLs and invalid geometry',()=>{const p={version:1,banners:[createBanner({})]};assert.equal(validateProject(p),p);p.banners[0].layers[0].w=NaN;assert.throws(()=>validateProject(p));p.banners[0].layers[0].w=100;p.draft={photo:'https://example.com/tracking.png'};assert.throws(()=>validateProject(p));delete p.draft;p.banners[0].layers[1].src='https://example.com/photo.jpg';assert.throws(()=>validateProject(p));});
test('Korean wrapping preserves characters and hard line breaks',()=>{const ctx={measureText:t=>({width:[...t].length*10})};assert.deepEqual(wrapText(ctx,'쿠팡알바\n주말근무',20),['쿠팡','알바','주말','근무']);});
test('ZIP archive contains valid UTF-8 filename and PNG byte data',async()=>{const zip=zipStore([{name:'배너.png',data:new Uint8Array([137,80,78,71])}]);const bytes=new Uint8Array(await zip.arrayBuffer()),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint16(6,true),0x0800);assert.equal(v.getUint32(bytes.length-22,true),0x06054b50);assert.equal(v.getUint16(bytes.length-14,true),1);});
